import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./global.css";
import { NoteProvider } from "./context/NoteContext";
import { FilterContextProvider } from "./context/FilterContext";
import { ClerkProvider } from "@clerk/nextjs";
import { dark, neobrutalism } from "@clerk/themes";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
type CustomChildrenProps = {
  children: React.ReactNode | React.ReactNode[];
};

export default function RootLayout({ children }: CustomChildrenProps) {
  return (
    <ClerkProvider
      appearance={{
        baseTheme: dark,
      }}
    >
      <html lang="en">
        <body className={inter.className}>
          <NoteProvider>
            {" "}
            <FilterContextProvider>{children}</FilterContextProvider>
          </NoteProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
